Repository jorgebucaran/hyperapp, pull requests merged in 2018-03, with the labels that each got.

#640 fix types according with ultradom types
  hyperapp.d.ts
Labels: TYPES

#638 Delegate DOM events to proxy.
  src/index.js
  test/dom.test.js
Labels: IMPROVEMENT, PERFORMANCE

#643 fix h types
  hyperapp.d.ts
Labels: IMPROVEMENT, TYPES

#644 Enter the dark side: rewrite some tests using JSX.
  package.json
  test/actions.test.js
  test/app.test.js
  test/dom.test.js
  test/lifecycle.test.js
  test/mounting.test.js
  test/recycling.test.js
  test/slices.test.js
  test/svg.test.js
Labels: TESTING

#639 Add docs for subviews.
  README.md
Labels: DOCS

#612 CSS Variables (Custom Properties) 💅
  src/index.js
  test/dom.test.js
Labels: FEATURE

#646 Another alternative to JSX.
  README.md
Labels: DOCS

#647 Improve Actions documentation
  README.md
Labels: DOCS, IMPROVEMENT

#651 Fix typos in README
  README.md
Labels: DOCS

#652 Add 'Available from...' to readme 'Lazy Components' section
  README.md
Labels: DOCS

#653 Added a couple of Tips to the Lifecylce Events section
  README.md
Labels: DOCS

#636 Allow Lazy components to return null as on the normal components
  hyperapp.d.ts
  src/index.js
  test/app.test.js
Labels: DISCUSSION, FIX, IMPROVEMENT

#659 Fix d.ts file as component can return VNode or View
  hyperapp.d.ts
  test/ts/Component.tsx
Labels: IMPROVEMENT, TYPES

#664 Format improvements
  hyperapp.d.ts
  package.json
  test/ts/Component.tsx
Labels: COMMUNITY

#670 Fix TS fails because of the use of ES6
  test/ts/tsconfig.json
Labels: FIX

#671 Add ci test for prettier use
  .travis.yml
Labels: IMPROVEMENT
