Repository jorgebucaran/hyperapp, pull requests merged in 2018-02, with the labels that each got.

#594 oldProps→oldAttributes in README.md
  README.md
Labels: DOCS

#603 Sanitation -> Sanitization
  README.md
Labels: DOCS, FIX

#614 Do not mutate initial state
  src/index.js
  test/slices.test.js
Labels: FIX

#623 Fix list assignment
  src/index.js
  test/dom.test.js
Labels: FIX

#606 Lazy components
  src/index.js
  test/components.test.js
  test/h.test.js
Labels: DISCUSSION, FEATURE

#624 !newKeyed[oldKeyed[i][1].key] -> !newKeyed[i]
  src/index.js
Labels: NEEDS FEEDBACK

#611 fix minify
  package.json
Labels: FIX
