Repository jorgebucaran/hyperapp, pull requests merged in 2021-04, with the labels that each got.

#1016 TypeScript definitions for 2.0.10
  docs/architecture/actions.md
  docs/architecture/subscriptions.md
  docs/architecture/views.md
  docs/reference.md
  index.d.ts
  package.json
Labels: enhancement, types

#1045 Types: enable definite payloads
  index.d.ts
Labels: types

#1046 Improved Dispatch docs
  docs/architecture/dispatch.md
Labels: docs

#1053 Fix edge cases for the type definition of `memo()`.
  index.d.ts
Labels: types

#1054 Improve direct usage of `EventActions`.
  index.d.ts
Labels: types
